# Generated by Django 4.1.3 on 2023-01-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
